name: CI/CD Pipeline for Spring App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests with Gradle
        run: ./gradlew clean test

      - name: Build Jar with Gradle
        run: ./gradlew build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 588738576341.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t springserver .
          docker tag springserver:latest 588738576341.dkr.ecr.us-east-1.amazonaws.com/humandelivery/springserver:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 588738576341.dkr.ecr.us-east-1.amazonaws.com/humandelivery/springserver:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/humandelivery
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 588738576341.dkr.ecr.us-east-1.amazonaws.com
            docker-compose pull spring
            docker-compose up -d spring
